// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateEntityInput struct {
	OrganizationID         string   `json:"organizationId"`
	EntityType             string   `json:"entityType"`
	Path                   *string  `json:"path,omitempty"`
	Properties             string   `json:"properties"`
	LinkedEntityID         *string  `json:"linkedEntityId,omitempty"`
	LinkedEntityIds        []string `json:"linkedEntityIds,omitempty"`
	LinkedEntityReference  *string  `json:"linkedEntityReference,omitempty"`
	LinkedEntityReferences []string `json:"linkedEntityReferences,omitempty"`
}

type CreateEntityJoinDefinitionInput struct {
	OrganizationID  string            `json:"organizationId"`
	Name            string            `json:"name"`
	Description     *string           `json:"description,omitempty"`
	JoinType        *JoinType         `json:"joinType,omitempty"`
	LeftEntityType  string            `json:"leftEntityType"`
	RightEntityType string            `json:"rightEntityType"`
	JoinField       *string           `json:"joinField,omitempty"`
	LeftFilters     []*PropertyFilter `json:"leftFilters,omitempty"`
	RightFilters    []*PropertyFilter `json:"rightFilters,omitempty"`
	SortCriteria    []*JoinSortInput  `json:"sortCriteria,omitempty"`
}

type CreateEntitySchemaInput struct {
	OrganizationID string                  `json:"organizationId"`
	Name           string                  `json:"name"`
	Description    *string                 `json:"description,omitempty"`
	Fields         []*FieldDefinitionInput `json:"fields"`
}

type CreateEntityTransformationInput struct {
	OrganizationID string                           `json:"organizationId"`
	Name           string                           `json:"name"`
	Description    *string                          `json:"description,omitempty"`
	Nodes          []*EntityTransformationNodeInput `json:"nodes"`
}

type CreateOrganizationInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Entity struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	SchemaID       string    `json:"schemaId"`
	EntityType     string    `json:"entityType"`
	Path           string    `json:"path"`
	Properties     string    `json:"properties"`
	ReferenceValue *string   `json:"referenceValue,omitempty"`
	Version        int       `json:"version"`
	CreatedAt      string    `json:"createdAt"`
	UpdatedAt      string    `json:"updatedAt"`
	LinkedEntities []*Entity `json:"linkedEntities"`
}

type EntityConnection struct {
	Entities []*Entity `json:"entities"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type EntityDiffResult struct {
	Base        *EntitySnapshotView `json:"base,omitempty"`
	Target      *EntitySnapshotView `json:"target,omitempty"`
	UnifiedDiff *string             `json:"unifiedDiff,omitempty"`
}

type EntityExportJob struct {
	ID                       string                  `json:"id"`
	OrganizationID           string                  `json:"organizationId"`
	JobType                  EntityExportJobType     `json:"jobType"`
	EntityType               *string                 `json:"entityType,omitempty"`
	TransformationID         *string                 `json:"transformationId,omitempty"`
	Status                   EntityExportJobStatus   `json:"status"`
	RowsRequested            int                     `json:"rowsRequested"`
	RowsExported             int                     `json:"rowsExported"`
	BytesWritten             int                     `json:"bytesWritten"`
	FileMimeType             *string                 `json:"fileMimeType,omitempty"`
	FileByteSize             *int                    `json:"fileByteSize,omitempty"`
	ErrorMessage             *string                 `json:"errorMessage,omitempty"`
	Filters                  []*PropertyFilterConfig `json:"filters"`
	TransformationDefinition *EntityTransformation   `json:"transformationDefinition,omitempty"`
	EnqueuedAt               string                  `json:"enqueuedAt"`
	StartedAt                *string                 `json:"startedAt,omitempty"`
	CompletedAt              *string                 `json:"completedAt,omitempty"`
	UpdatedAt                string                  `json:"updatedAt"`
	DownloadURL              *string                 `json:"downloadUrl,omitempty"`
}

type EntityExportLog struct {
	ID             string  `json:"id"`
	ExportJobID    string  `json:"exportJobId"`
	OrganizationID string  `json:"organizationId"`
	RowIdentifier  *string `json:"rowIdentifier,omitempty"`
	ErrorMessage   string  `json:"errorMessage"`
	CreatedAt      string  `json:"createdAt"`
}

type EntityFilter struct {
	EntityType      *string           `json:"entityType,omitempty"`
	PropertyFilters []*PropertyFilter `json:"propertyFilters,omitempty"`
	TextSearch      *string           `json:"textSearch,omitempty"`
	PathFilter      *PathFilter       `json:"pathFilter,omitempty"`
}

type EntityHierarchy struct {
	Current   *Entity   `json:"current"`
	Ancestors []*Entity `json:"ancestors"`
	Children  []*Entity `json:"children"`
	Siblings  []*Entity `json:"siblings"`
}

type EntityJoinConnection struct {
	Edges    []*EntityJoinEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type EntityJoinDefinition struct {
	ID              string                  `json:"id"`
	OrganizationID  string                  `json:"organizationId"`
	Name            string                  `json:"name"`
	Description     *string                 `json:"description,omitempty"`
	LeftEntityType  string                  `json:"leftEntityType"`
	RightEntityType string                  `json:"rightEntityType"`
	JoinType        JoinType                `json:"joinType"`
	JoinField       *string                 `json:"joinField,omitempty"`
	JoinFieldType   *FieldType              `json:"joinFieldType,omitempty"`
	LeftFilters     []*PropertyFilterConfig `json:"leftFilters"`
	RightFilters    []*PropertyFilterConfig `json:"rightFilters"`
	SortCriteria    []*JoinSortCriterion    `json:"sortCriteria"`
	CreatedAt       string                  `json:"createdAt"`
	UpdatedAt       string                  `json:"updatedAt"`
}

type EntityJoinEdge struct {
	Left  *Entity `json:"left"`
	Right *Entity `json:"right"`
}

type EntitySchema struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	Name              string             `json:"name"`
	Description       *string            `json:"description,omitempty"`
	Fields            []*FieldDefinition `json:"fields"`
	Version           string             `json:"version"`
	Status            SchemaStatus       `json:"status"`
	PreviousVersionID *string            `json:"previousVersionId,omitempty"`
	CreatedAt         string             `json:"createdAt"`
	UpdatedAt         string             `json:"updatedAt"`
}

type EntitySnapshotView struct {
	Version       int      `json:"version"`
	Path          string   `json:"path"`
	SchemaID      string   `json:"schemaId"`
	EntityType    string   `json:"entityType"`
	CanonicalText []string `json:"canonicalText"`
}

type EntitySortInput struct {
	Field       EntitySortField `json:"field"`
	Direction   *SortDirection  `json:"direction,omitempty"`
	PropertyKey *string         `json:"propertyKey,omitempty"`
}

type EntityTransformation struct {
	ID             string                      `json:"id"`
	OrganizationID string                      `json:"organizationId"`
	Name           string                      `json:"name"`
	Description    *string                     `json:"description,omitempty"`
	Nodes          []*EntityTransformationNode `json:"nodes"`
	CreatedAt      string                      `json:"createdAt"`
	UpdatedAt      string                      `json:"updatedAt"`
}

type EntityTransformationConnection struct {
	Edges    []*EntityTransformationRecordEdge `json:"edges"`
	PageInfo *PageInfo                         `json:"pageInfo"`
}

type EntityTransformationFilterConfig struct {
	Alias   string                  `json:"alias"`
	Filters []*PropertyFilterConfig `json:"filters"`
}

type EntityTransformationFilterConfigInput struct {
	Alias   string            `json:"alias"`
	Filters []*PropertyFilter `json:"filters,omitempty"`
}

type EntityTransformationJoinConfig struct {
	LeftAlias  string `json:"leftAlias"`
	RightAlias string `json:"rightAlias"`
	OnField    string `json:"onField"`
}

type EntityTransformationJoinConfigInput struct {
	LeftAlias  string `json:"leftAlias"`
	RightAlias string `json:"rightAlias"`
	OnField    string `json:"onField"`
}

type EntityTransformationLoadConfig struct {
	Alias      string                  `json:"alias"`
	EntityType string                  `json:"entityType"`
	Filters    []*PropertyFilterConfig `json:"filters"`
}

type EntityTransformationLoadConfigInput struct {
	Alias      string            `json:"alias"`
	EntityType string            `json:"entityType"`
	Filters    []*PropertyFilter `json:"filters,omitempty"`
}

type EntityTransformationMaterializeConfig struct {
	Outputs []*EntityTransformationMaterializeOutput `json:"outputs"`
}

type EntityTransformationMaterializeConfigInput struct {
	Outputs []*EntityTransformationMaterializeOutputInput `json:"outputs"`
}

type EntityTransformationMaterializeFieldMapping struct {
	SourceAlias string `json:"sourceAlias"`
	SourceField string `json:"sourceField"`
	OutputField string `json:"outputField"`
}

type EntityTransformationMaterializeFieldMappingInput struct {
	SourceAlias string `json:"sourceAlias"`
	SourceField string `json:"sourceField"`
	OutputField string `json:"outputField"`
}

type EntityTransformationMaterializeOutput struct {
	Alias  string                                         `json:"alias"`
	Fields []*EntityTransformationMaterializeFieldMapping `json:"fields"`
}

type EntityTransformationMaterializeOutputInput struct {
	Alias  string                                              `json:"alias"`
	Fields []*EntityTransformationMaterializeFieldMappingInput `json:"fields"`
}

type EntityTransformationNode struct {
	ID          string                                 `json:"id"`
	Name        string                                 `json:"name"`
	Type        EntityTransformationNodeType           `json:"type"`
	Inputs      []string                               `json:"inputs"`
	Load        *EntityTransformationLoadConfig        `json:"load,omitempty"`
	Filter      *EntityTransformationFilterConfig      `json:"filter,omitempty"`
	Project     *EntityTransformationProjectConfig     `json:"project,omitempty"`
	Join        *EntityTransformationJoinConfig        `json:"join,omitempty"`
	Materialize *EntityTransformationMaterializeConfig `json:"materialize,omitempty"`
	Sort        *EntityTransformationSortConfig        `json:"sort,omitempty"`
	Paginate    *EntityTransformationPaginateConfig    `json:"paginate,omitempty"`
}

type EntityTransformationNodeInput struct {
	ID          *string                                     `json:"id,omitempty"`
	Name        string                                      `json:"name"`
	Type        EntityTransformationNodeType                `json:"type"`
	Inputs      []string                                    `json:"inputs,omitempty"`
	Load        *EntityTransformationLoadConfigInput        `json:"load,omitempty"`
	Filter      *EntityTransformationFilterConfigInput      `json:"filter,omitempty"`
	Project     *EntityTransformationProjectConfigInput     `json:"project,omitempty"`
	Join        *EntityTransformationJoinConfigInput        `json:"join,omitempty"`
	Materialize *EntityTransformationMaterializeConfigInput `json:"materialize,omitempty"`
	Sort        *EntityTransformationSortConfigInput        `json:"sort,omitempty"`
	Paginate    *EntityTransformationPaginateConfigInput    `json:"paginate,omitempty"`
}

type EntityTransformationPaginateConfig struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type EntityTransformationPaginateConfigInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type EntityTransformationProjectConfig struct {
	Alias  string   `json:"alias"`
	Fields []string `json:"fields"`
}

type EntityTransformationProjectConfigInput struct {
	Alias  string   `json:"alias"`
	Fields []string `json:"fields"`
}

type EntityTransformationRecordEdge struct {
	Entities []*EntityTransformationRecordEntity `json:"entities"`
}

type EntityTransformationRecordEntity struct {
	Alias  string  `json:"alias"`
	Entity *Entity `json:"entity,omitempty"`
}

type EntityTransformationSortConfig struct {
	Alias     string            `json:"alias"`
	Field     string            `json:"field"`
	Direction JoinSortDirection `json:"direction"`
}

type EntityTransformationSortConfigInput struct {
	Alias     string            `json:"alias"`
	Field     string            `json:"field"`
	Direction JoinSortDirection `json:"direction"`
}

type ExecuteEntityJoinInput struct {
	JoinID       string            `json:"joinId"`
	LeftFilters  []*PropertyFilter `json:"leftFilters,omitempty"`
	RightFilters []*PropertyFilter `json:"rightFilters,omitempty"`
	SortCriteria []*JoinSortInput  `json:"sortCriteria,omitempty"`
	Pagination   *PaginationInput  `json:"pagination,omitempty"`
}

type ExecuteEntityTransformationInput struct {
	TransformationID string           `json:"transformationId"`
	Pagination       *PaginationInput `json:"pagination,omitempty"`
}

type FieldDefinition struct {
	Name                string    `json:"name"`
	Type                FieldType `json:"type"`
	Required            bool      `json:"required"`
	Description         *string   `json:"description,omitempty"`
	Default             *string   `json:"default,omitempty"`
	Validation          *string   `json:"validation,omitempty"`
	ReferenceEntityType *string   `json:"referenceEntityType,omitempty"`
}

type FieldDefinitionInput struct {
	Name                string    `json:"name"`
	Type                FieldType `json:"type"`
	Required            *bool     `json:"required,omitempty"`
	Description         *string   `json:"description,omitempty"`
	Default             *string   `json:"default,omitempty"`
	Validation          *string   `json:"validation,omitempty"`
	ReferenceEntityType *string   `json:"referenceEntityType,omitempty"`
}

type JoinSortCriterion struct {
	Side      JoinSide          `json:"side"`
	Field     string            `json:"field"`
	Direction JoinSortDirection `json:"direction"`
}

type JoinSortInput struct {
	Side      JoinSide           `json:"side"`
	Field     string             `json:"field"`
	Direction *JoinSortDirection `json:"direction,omitempty"`
}

type Mutation struct {
}

type Organization struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
	TotalCount      int  `json:"totalCount"`
}

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type PathFilter struct {
	AncestorsOf   *string `json:"ancestorsOf,omitempty"`
	DescendantsOf *string `json:"descendantsOf,omitempty"`
	ChildrenOf    *string `json:"childrenOf,omitempty"`
	SiblingsOf    *string `json:"siblingsOf,omitempty"`
}

type PropertyFilter struct {
	Key     string   `json:"key"`
	Value   *string  `json:"value,omitempty"`
	Exists  *bool    `json:"exists,omitempty"`
	InArray []string `json:"inArray,omitempty"`
}

type PropertyFilterConfig struct {
	Key     string   `json:"key"`
	Value   *string  `json:"value,omitempty"`
	Exists  *bool    `json:"exists,omitempty"`
	InArray []string `json:"inArray,omitempty"`
}

type Query struct {
}

type QueueEntityTypeExportInput struct {
	OrganizationID string            `json:"organizationId"`
	EntityType     string            `json:"entityType"`
	Filters        []*PropertyFilter `json:"filters,omitempty"`
}

type QueueTransformationExportInput struct {
	OrganizationID   string                               `json:"organizationId"`
	TransformationID string                               `json:"transformationId"`
	Filters          []*PropertyFilter                    `json:"filters,omitempty"`
	Options          *TransformationExecutionOptionsInput `json:"options,omitempty"`
}

type TransformationExecutionColumn struct {
	Key         string `json:"key"`
	Alias       string `json:"alias"`
	Field       string `json:"field"`
	Label       string `json:"label"`
	SourceAlias string `json:"sourceAlias"`
	SourceField string `json:"sourceField"`
}

type TransformationExecutionConnection struct {
	Columns  []*TransformationExecutionColumn `json:"columns"`
	Rows     []*TransformationExecutionRow    `json:"rows"`
	PageInfo *PageInfo                        `json:"pageInfo"`
}

type TransformationExecutionFilterInput struct {
	Alias   string   `json:"alias"`
	Field   string   `json:"field"`
	Value   *string  `json:"value,omitempty"`
	Exists  *bool    `json:"exists,omitempty"`
	InArray []string `json:"inArray,omitempty"`
}

type TransformationExecutionOptionsInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type TransformationExecutionRow struct {
	Values []*TransformationExecutionValue `json:"values"`
}

type TransformationExecutionSortInput struct {
	Alias     string         `json:"alias"`
	Field     string         `json:"field"`
	Direction *SortDirection `json:"direction,omitempty"`
}

type TransformationExecutionValue struct {
	ColumnKey string  `json:"columnKey"`
	Value     *string `json:"value,omitempty"`
}

type UpdateEntityInput struct {
	ID         string  `json:"id"`
	EntityType *string `json:"entityType,omitempty"`
	Path       *string `json:"path,omitempty"`
	Properties *string `json:"properties,omitempty"`
}

type UpdateEntityJoinDefinitionInput struct {
	ID              string            `json:"id"`
	Name            *string           `json:"name,omitempty"`
	Description     *string           `json:"description,omitempty"`
	JoinType        *JoinType         `json:"joinType,omitempty"`
	LeftEntityType  *string           `json:"leftEntityType,omitempty"`
	RightEntityType *string           `json:"rightEntityType,omitempty"`
	JoinField       *string           `json:"joinField,omitempty"`
	LeftFilters     []*PropertyFilter `json:"leftFilters,omitempty"`
	RightFilters    []*PropertyFilter `json:"rightFilters,omitempty"`
	SortCriteria    []*JoinSortInput  `json:"sortCriteria,omitempty"`
}

type UpdateEntitySchemaInput struct {
	ID          string                  `json:"id"`
	Name        *string                 `json:"name,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Fields      []*FieldDefinitionInput `json:"fields,omitempty"`
}

type UpdateEntityTransformationInput struct {
	ID          string                           `json:"id"`
	Name        *string                          `json:"name,omitempty"`
	Description *string                          `json:"description,omitempty"`
	Nodes       []*EntityTransformationNodeInput `json:"nodes,omitempty"`
}

type UpdateOrganizationInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type ValidationResult struct {
	IsValid  bool     `json:"isValid"`
	Errors   []string `json:"errors"`
	Warnings []string `json:"warnings"`
}

type EntityExportJobStatus string

const (
	EntityExportJobStatusPending   EntityExportJobStatus = "PENDING"
	EntityExportJobStatusRunning   EntityExportJobStatus = "RUNNING"
	EntityExportJobStatusCompleted EntityExportJobStatus = "COMPLETED"
	EntityExportJobStatusCancelled EntityExportJobStatus = "CANCELLED"
	EntityExportJobStatusFailed    EntityExportJobStatus = "FAILED"
)

var AllEntityExportJobStatus = []EntityExportJobStatus{
	EntityExportJobStatusPending,
	EntityExportJobStatusRunning,
	EntityExportJobStatusCompleted,
	EntityExportJobStatusCancelled,
	EntityExportJobStatusFailed,
}

func (e EntityExportJobStatus) IsValid() bool {
	switch e {
	case EntityExportJobStatusPending, EntityExportJobStatusRunning, EntityExportJobStatusCompleted, EntityExportJobStatusCancelled, EntityExportJobStatusFailed:
		return true
	}
	return false
}

func (e EntityExportJobStatus) String() string {
	return string(e)
}

func (e *EntityExportJobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntityExportJobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntityExportJobStatus", str)
	}
	return nil
}

func (e EntityExportJobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntityExportJobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntityExportJobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntityExportJobType string

const (
	EntityExportJobTypeEntityType     EntityExportJobType = "ENTITY_TYPE"
	EntityExportJobTypeTransformation EntityExportJobType = "TRANSFORMATION"
)

var AllEntityExportJobType = []EntityExportJobType{
	EntityExportJobTypeEntityType,
	EntityExportJobTypeTransformation,
}

func (e EntityExportJobType) IsValid() bool {
	switch e {
	case EntityExportJobTypeEntityType, EntityExportJobTypeTransformation:
		return true
	}
	return false
}

func (e EntityExportJobType) String() string {
	return string(e)
}

func (e *EntityExportJobType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntityExportJobType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntityExportJobType", str)
	}
	return nil
}

func (e EntityExportJobType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntityExportJobType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntityExportJobType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntitySortField string

const (
	EntitySortFieldCreatedAt  EntitySortField = "CREATED_AT"
	EntitySortFieldUpdatedAt  EntitySortField = "UPDATED_AT"
	EntitySortFieldEntityType EntitySortField = "ENTITY_TYPE"
	EntitySortFieldPath       EntitySortField = "PATH"
	EntitySortFieldVersion    EntitySortField = "VERSION"
	EntitySortFieldProperty   EntitySortField = "PROPERTY"
)

var AllEntitySortField = []EntitySortField{
	EntitySortFieldCreatedAt,
	EntitySortFieldUpdatedAt,
	EntitySortFieldEntityType,
	EntitySortFieldPath,
	EntitySortFieldVersion,
	EntitySortFieldProperty,
}

func (e EntitySortField) IsValid() bool {
	switch e {
	case EntitySortFieldCreatedAt, EntitySortFieldUpdatedAt, EntitySortFieldEntityType, EntitySortFieldPath, EntitySortFieldVersion, EntitySortFieldProperty:
		return true
	}
	return false
}

func (e EntitySortField) String() string {
	return string(e)
}

func (e *EntitySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntitySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntitySortField", str)
	}
	return nil
}

func (e EntitySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntitySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntitySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntityTransformationNodeType string

const (
	EntityTransformationNodeTypeLoad        EntityTransformationNodeType = "LOAD"
	EntityTransformationNodeTypeFilter      EntityTransformationNodeType = "FILTER"
	EntityTransformationNodeTypeProject     EntityTransformationNodeType = "PROJECT"
	EntityTransformationNodeTypeJoin        EntityTransformationNodeType = "JOIN"
	EntityTransformationNodeTypeLeftJoin    EntityTransformationNodeType = "LEFT_JOIN"
	EntityTransformationNodeTypeAntiJoin    EntityTransformationNodeType = "ANTI_JOIN"
	EntityTransformationNodeTypeUnion       EntityTransformationNodeType = "UNION"
	EntityTransformationNodeTypeMaterialize EntityTransformationNodeType = "MATERIALIZE"
	EntityTransformationNodeTypeSort        EntityTransformationNodeType = "SORT"
	EntityTransformationNodeTypePaginate    EntityTransformationNodeType = "PAGINATE"
)

var AllEntityTransformationNodeType = []EntityTransformationNodeType{
	EntityTransformationNodeTypeLoad,
	EntityTransformationNodeTypeFilter,
	EntityTransformationNodeTypeProject,
	EntityTransformationNodeTypeJoin,
	EntityTransformationNodeTypeLeftJoin,
	EntityTransformationNodeTypeAntiJoin,
	EntityTransformationNodeTypeUnion,
	EntityTransformationNodeTypeMaterialize,
	EntityTransformationNodeTypeSort,
	EntityTransformationNodeTypePaginate,
}

func (e EntityTransformationNodeType) IsValid() bool {
	switch e {
	case EntityTransformationNodeTypeLoad, EntityTransformationNodeTypeFilter, EntityTransformationNodeTypeProject, EntityTransformationNodeTypeJoin, EntityTransformationNodeTypeLeftJoin, EntityTransformationNodeTypeAntiJoin, EntityTransformationNodeTypeUnion, EntityTransformationNodeTypeMaterialize, EntityTransformationNodeTypeSort, EntityTransformationNodeTypePaginate:
		return true
	}
	return false
}

func (e EntityTransformationNodeType) String() string {
	return string(e)
}

func (e *EntityTransformationNodeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntityTransformationNodeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntityTransformationNodeType", str)
	}
	return nil
}

func (e EntityTransformationNodeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntityTransformationNodeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntityTransformationNodeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FieldType string

const (
	FieldTypeString               FieldType = "STRING"
	FieldTypeInteger              FieldType = "INTEGER"
	FieldTypeFloat                FieldType = "FLOAT"
	FieldTypeBoolean              FieldType = "BOOLEAN"
	FieldTypeTimestamp            FieldType = "TIMESTAMP"
	FieldTypeJSON                 FieldType = "JSON"
	FieldTypeFileReference        FieldType = "FILE_REFERENCE"
	FieldTypeGeometry             FieldType = "GEOMETRY"
	FieldTypeTimeseries           FieldType = "TIMESERIES"
	FieldTypeReference            FieldType = "REFERENCE"
	FieldTypeEntityReference      FieldType = "ENTITY_REFERENCE"
	FieldTypeEntityReferenceArray FieldType = "ENTITY_REFERENCE_ARRAY"
)

var AllFieldType = []FieldType{
	FieldTypeString,
	FieldTypeInteger,
	FieldTypeFloat,
	FieldTypeBoolean,
	FieldTypeTimestamp,
	FieldTypeJSON,
	FieldTypeFileReference,
	FieldTypeGeometry,
	FieldTypeTimeseries,
	FieldTypeReference,
	FieldTypeEntityReference,
	FieldTypeEntityReferenceArray,
}

func (e FieldType) IsValid() bool {
	switch e {
	case FieldTypeString, FieldTypeInteger, FieldTypeFloat, FieldTypeBoolean, FieldTypeTimestamp, FieldTypeJSON, FieldTypeFileReference, FieldTypeGeometry, FieldTypeTimeseries, FieldTypeReference, FieldTypeEntityReference, FieldTypeEntityReferenceArray:
		return true
	}
	return false
}

func (e FieldType) String() string {
	return string(e)
}

func (e *FieldType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FieldType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FieldType", str)
	}
	return nil
}

func (e FieldType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FieldType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FieldType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JoinSide string

const (
	JoinSideLeft  JoinSide = "LEFT"
	JoinSideRight JoinSide = "RIGHT"
)

var AllJoinSide = []JoinSide{
	JoinSideLeft,
	JoinSideRight,
}

func (e JoinSide) IsValid() bool {
	switch e {
	case JoinSideLeft, JoinSideRight:
		return true
	}
	return false
}

func (e JoinSide) String() string {
	return string(e)
}

func (e *JoinSide) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JoinSide(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JoinSide", str)
	}
	return nil
}

func (e JoinSide) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JoinSide) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JoinSide) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JoinSortDirection string

const (
	JoinSortDirectionAsc  JoinSortDirection = "ASC"
	JoinSortDirectionDesc JoinSortDirection = "DESC"
)

var AllJoinSortDirection = []JoinSortDirection{
	JoinSortDirectionAsc,
	JoinSortDirectionDesc,
}

func (e JoinSortDirection) IsValid() bool {
	switch e {
	case JoinSortDirectionAsc, JoinSortDirectionDesc:
		return true
	}
	return false
}

func (e JoinSortDirection) String() string {
	return string(e)
}

func (e *JoinSortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JoinSortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JoinSortDirection", str)
	}
	return nil
}

func (e JoinSortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JoinSortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JoinSortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JoinType string

const (
	JoinTypeReference JoinType = "REFERENCE"
	JoinTypeCross     JoinType = "CROSS"
)

var AllJoinType = []JoinType{
	JoinTypeReference,
	JoinTypeCross,
}

func (e JoinType) IsValid() bool {
	switch e {
	case JoinTypeReference, JoinTypeCross:
		return true
	}
	return false
}

func (e JoinType) String() string {
	return string(e)
}

func (e *JoinType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JoinType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JoinType", str)
	}
	return nil
}

func (e JoinType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JoinType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JoinType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SchemaStatus string

const (
	SchemaStatusActive     SchemaStatus = "ACTIVE"
	SchemaStatusDeprecated SchemaStatus = "DEPRECATED"
	SchemaStatusArchived   SchemaStatus = "ARCHIVED"
	SchemaStatusDraft      SchemaStatus = "DRAFT"
)

var AllSchemaStatus = []SchemaStatus{
	SchemaStatusActive,
	SchemaStatusDeprecated,
	SchemaStatusArchived,
	SchemaStatusDraft,
}

func (e SchemaStatus) IsValid() bool {
	switch e {
	case SchemaStatusActive, SchemaStatusDeprecated, SchemaStatusArchived, SchemaStatusDraft:
		return true
	}
	return false
}

func (e SchemaStatus) String() string {
	return string(e)
}

func (e *SchemaStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SchemaStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SchemaStatus", str)
	}
	return nil
}

func (e SchemaStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SchemaStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SchemaStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
