// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entity_export_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const GetEntityExportJobByID = `-- name: GetEntityExportJobByID :one
SELECT
    id,
    organization_id,
    job_type,
    entity_type,
    transformation_id,
    filters,
    rows_requested,
    rows_exported,
    bytes_written,
    file_path,
    file_mime_type,
    file_byte_size,
    status,
    error_message,
    enqueued_at,
    started_at,
    completed_at,
    updated_at,
    transformation_definition,
    transformation_options
FROM entity_export_jobs
WHERE id = $1
`

func (q *Queries) GetEntityExportJobByID(ctx context.Context, id uuid.UUID) (EntityExportJob, error) {
	row := q.db.QueryRow(ctx, GetEntityExportJobByID, id)
	var i EntityExportJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.JobType,
		&i.EntityType,
		&i.TransformationID,
		&i.Filters,
		&i.RowsRequested,
		&i.RowsExported,
		&i.BytesWritten,
		&i.FilePath,
		&i.FileMimeType,
		&i.FileByteSize,
		&i.Status,
		&i.ErrorMessage,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.TransformationDefinition,
		&i.TransformationOptions,
	)
	return i, err
}

const InsertEntityExportJob = `-- name: InsertEntityExportJob :exec

INSERT INTO entity_export_jobs (
    id,
    organization_id,
    job_type,
    entity_type,
    transformation_id,
    filters,
    rows_requested,
    status,
    transformation_definition,
    transformation_options
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'PENDING',
    $8,
    $9
)
`

type InsertEntityExportJobParams struct {
	ID                       uuid.UUID   `json:"id"`
	OrganizationID           uuid.UUID   `json:"organization_id"`
	JobType                  string      `json:"job_type"`
	EntityType               pgtype.Text `json:"entity_type"`
	TransformationID         pgtype.UUID `json:"transformation_id"`
	Filters                  []byte      `json:"filters"`
	RowsRequested            int32       `json:"rows_requested"`
	TransformationDefinition []byte      `json:"transformation_definition"`
	TransformationOptions    []byte      `json:"transformation_options"`
}

// Track background export jobs for entities.
func (q *Queries) InsertEntityExportJob(ctx context.Context, arg InsertEntityExportJobParams) error {
	_, err := q.db.Exec(ctx, InsertEntityExportJob,
		arg.ID,
		arg.OrganizationID,
		arg.JobType,
		arg.EntityType,
		arg.TransformationID,
		arg.Filters,
		arg.RowsRequested,
		arg.TransformationDefinition,
		arg.TransformationOptions,
	)
	return err
}

const InsertEntityExportLog = `-- name: InsertEntityExportLog :exec
INSERT INTO entity_export_logs (
    export_job_id,
    organization_id,
    row_identifier,
    error_message
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertEntityExportLogParams struct {
	ExportJobID    uuid.UUID   `json:"export_job_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	RowIdentifier  pgtype.Text `json:"row_identifier"`
	ErrorMessage   string      `json:"error_message"`
}

func (q *Queries) InsertEntityExportLog(ctx context.Context, arg InsertEntityExportLogParams) error {
	_, err := q.db.Exec(ctx, InsertEntityExportLog,
		arg.ExportJobID,
		arg.OrganizationID,
		arg.RowIdentifier,
		arg.ErrorMessage,
	)
	return err
}

const ListEntityExportJobsByStatus = `-- name: ListEntityExportJobsByStatus :many
SELECT
    id,
    organization_id,
    job_type,
    entity_type,
    transformation_id,
    filters,
    rows_requested,
    rows_exported,
    bytes_written,
    file_path,
    file_mime_type,
    file_byte_size,
    status,
    error_message,
    enqueued_at,
    started_at,
    completed_at,
    updated_at,
    transformation_definition,
    transformation_options
FROM entity_export_jobs
WHERE status = ANY($1::text[])
  AND ($2::uuid IS NULL OR organization_id = $2)
ORDER BY enqueued_at DESC
LIMIT $4 OFFSET $3
`

type ListEntityExportJobsByStatusParams struct {
	Statuses       []string    `json:"statuses"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) ListEntityExportJobsByStatus(ctx context.Context, arg ListEntityExportJobsByStatusParams) ([]EntityExportJob, error) {
	rows, err := q.db.Query(ctx, ListEntityExportJobsByStatus,
		arg.Statuses,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityExportJob{}
	for rows.Next() {
		var i EntityExportJob
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.JobType,
			&i.EntityType,
			&i.TransformationID,
			&i.Filters,
			&i.RowsRequested,
			&i.RowsExported,
			&i.BytesWritten,
			&i.FilePath,
			&i.FileMimeType,
			&i.FileByteSize,
			&i.Status,
			&i.ErrorMessage,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.TransformationDefinition,
			&i.TransformationOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEntityExportLogsForJob = `-- name: ListEntityExportLogsForJob :many
SELECT
    id,
    export_job_id,
    organization_id,
    row_identifier,
    error_message,
    created_at
FROM entity_export_logs
WHERE export_job_id = $1
ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type ListEntityExportLogsForJobParams struct {
	ExportJobID uuid.UUID `json:"export_job_id"`
	PageOffset  int32     `json:"page_offset"`
	PageLimit   int32     `json:"page_limit"`
}

func (q *Queries) ListEntityExportLogsForJob(ctx context.Context, arg ListEntityExportLogsForJobParams) ([]EntityExportLog, error) {
	rows, err := q.db.Query(ctx, ListEntityExportLogsForJob, arg.ExportJobID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityExportLog{}
	for rows.Next() {
		var i EntityExportLog
		if err := rows.Scan(
			&i.ID,
			&i.ExportJobID,
			&i.OrganizationID,
			&i.RowIdentifier,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkEntityExportJobCancelled = `-- name: MarkEntityExportJobCancelled :execrows
UPDATE entity_export_jobs
SET status = 'CANCELLED',
    error_message = $1,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $2
  AND status IN ('PENDING', 'RUNNING')
`

type MarkEntityExportJobCancelledParams struct {
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) MarkEntityExportJobCancelled(ctx context.Context, arg MarkEntityExportJobCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkEntityExportJobCancelled, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const MarkEntityExportJobCompleted = `-- name: MarkEntityExportJobCompleted :exec
UPDATE entity_export_jobs
SET status = 'COMPLETED',
    rows_exported = $1,
    bytes_written = $2,
    file_path = $3,
    file_mime_type = $4,
    file_byte_size = $5,
    rows_requested = GREATEST(rows_requested, $1),
    completed_at = NOW(),
    updated_at = NOW(),
    error_message = NULL
WHERE id = $6
`

type MarkEntityExportJobCompletedParams struct {
	RowsExported int32       `json:"rows_exported"`
	BytesWritten int64       `json:"bytes_written"`
	FilePath     pgtype.Text `json:"file_path"`
	FileMimeType pgtype.Text `json:"file_mime_type"`
	FileByteSize pgtype.Int8 `json:"file_byte_size"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) MarkEntityExportJobCompleted(ctx context.Context, arg MarkEntityExportJobCompletedParams) error {
	_, err := q.db.Exec(ctx, MarkEntityExportJobCompleted,
		arg.RowsExported,
		arg.BytesWritten,
		arg.FilePath,
		arg.FileMimeType,
		arg.FileByteSize,
		arg.ID,
	)
	return err
}

const MarkEntityExportJobFailed = `-- name: MarkEntityExportJobFailed :exec
UPDATE entity_export_jobs
SET status = 'FAILED',
    error_message = $1,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $2
`

type MarkEntityExportJobFailedParams struct {
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) MarkEntityExportJobFailed(ctx context.Context, arg MarkEntityExportJobFailedParams) error {
	_, err := q.db.Exec(ctx, MarkEntityExportJobFailed, arg.ErrorMessage, arg.ID)
	return err
}

const MarkEntityExportJobRunning = `-- name: MarkEntityExportJobRunning :execrows
UPDATE entity_export_jobs
SET status = 'RUNNING',
    started_at = COALESCE(started_at, NOW()),
    updated_at = NOW()
WHERE id = $1
  AND status = 'PENDING'
`

func (q *Queries) MarkEntityExportJobRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, MarkEntityExportJobRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpdateEntityExportJobProgress = `-- name: UpdateEntityExportJobProgress :exec
UPDATE entity_export_jobs
SET rows_exported = $1,
    rows_requested = GREATEST(
        rows_requested,
        $1,
        COALESCE($2::INTEGER, rows_requested)
    ),
    bytes_written = $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateEntityExportJobProgressParams struct {
	RowsExported  int32       `json:"rows_exported"`
	RowsRequested pgtype.Int4 `json:"rows_requested"`
	BytesWritten  int64       `json:"bytes_written"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateEntityExportJobProgress(ctx context.Context, arg UpdateEntityExportJobProgressParams) error {
	_, err := q.db.Exec(ctx, UpdateEntityExportJobProgress,
		arg.RowsExported,
		arg.RowsRequested,
		arg.BytesWritten,
		arg.ID,
	)
	return err
}
