// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateEntitySchema(ctx context.Context, arg CreateEntitySchemaParams) (EntitySchema, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	DeleteEntity(ctx context.Context, id uuid.UUID) error
	DeleteEntitySchema(ctx context.Context, id uuid.UUID) error
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	FilterEntitiesByProperty(ctx context.Context, arg FilterEntitiesByPropertyParams) ([]Entity, error)
	GetEntitiesByIDs(ctx context.Context, ids []uuid.UUID) ([]Entity, error)
	GetEntity(ctx context.Context, id uuid.UUID) (Entity, error)
	GetEntityAncestors(ctx context.Context, arg GetEntityAncestorsParams) ([]Entity, error)
	GetEntityChildren(ctx context.Context, arg GetEntityChildrenParams) ([]Entity, error)
	GetEntityCount(ctx context.Context, organizationID uuid.UUID) (int64, error)
	GetEntityCountByType(ctx context.Context, arg GetEntityCountByTypeParams) (int64, error)
	GetEntityDescendants(ctx context.Context, arg GetEntityDescendantsParams) ([]Entity, error)
	GetEntitySchema(ctx context.Context, id uuid.UUID) (EntitySchema, error)
	GetEntitySchemaByName(ctx context.Context, arg GetEntitySchemaByNameParams) (EntitySchema, error)
	GetEntitySiblings(ctx context.Context, arg GetEntitySiblingsParams) ([]Entity, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	ListEntities(ctx context.Context, arg ListEntitiesParams) ([]ListEntitiesRow, error)
	ListEntitiesByType(ctx context.Context, arg ListEntitiesByTypeParams) ([]Entity, error)
	ListEntitySchemas(ctx context.Context, organizationID uuid.UUID) ([]EntitySchema, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	SchemaExists(ctx context.Context, arg SchemaExistsParams) (bool, error)
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
	UpdateEntitySchema(ctx context.Context, arg UpdateEntitySchemaParams) (EntitySchema, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
}

var _ Querier = (*Queries)(nil)
